import logging
from typing import Callable, Union
from typing import List, Optional

from .node import Node
from .sampling_config import SamplingConfig
from .stores import DataStore

log = logging.getLogger(__name__)

ResourceBuilder = Callable[
    ["BuilderEnvironment"],
    "Union[ResourcePool, list[ResourcePool], Awaitable[Union[ResourcePool, list[ResourcePool]]]]"
]


class NodeConfig:
    """
    The description of a calculation node used to build the calculation graph.

    Attributes:
        node: The calculation node (must implement Protocol `Node`).
        id: Optional id for the node, defaults to Node classname or Node id if specified.
        data_store: A callable that returns a DataStore for caching of results of the node.
        batch_size: Number of items that will be provided to the node as a batch.
        resource_builder: Optional function or object to build the execution environment.
        queue_size: Max queue size of the node for processing - if it is filled up by predecessor nodes, this node will first need to process items before predecessors may continue.
        greedy: If True, the node is considered a mandatory node for execution upon building the graph in BenchmarkManager.
        step: Execution step from which on the node should be active - if step is below, the node and nodes depending on it will be disabled.
        sampling_config: Configuration for sampling - needs to be provided by all nodes that require a sampling dependencies (indicated by `sampled_` prefix)
        always_recompute: If the node has a store, it will always be cleared at the start of the benchmark, resulting in recomputation of the node for all items.
    """

    base_config: Optional[dict] = None  # Class-level default config

    def __init__(
            self,
            node: Node,
            id: Optional[str] = None,
            data_store: Optional[Callable[..., DataStore]] = None,
            batch_size: Optional[int] = None,
            resource_builder: Optional[ResourceBuilder] = None,
            max_tasks: Optional[int] = None,
            queue_size: Optional[int] = None,
            greedy: bool = False,
            sampling_config: SamplingConfig = None,
            step: int = 1,
            always_recompute: bool = False
    ):
        base = NodeConfig.base_config or {}

        self.node = node
        self.always_recompute = always_recompute
        self.resource_builder = resource_builder
        self.data_store: Optional[Callable[..., DataStore]] = data_store
        self.batch_size: Optional[int] = batch_size or base.get("batch_size")
        self.max_tasks: Optional[int] = max_tasks or base.get("max_tasks")
        self.queue_size: Optional[int] = queue_size or base.get("queue_size")
        self.greedy: bool = greedy
        self.step = step
        self._id = id
        self.sampling_config = sampling_config

        if self.is_sampling():
            assert sampling_config is not None, "If Node uses sampling, it is necessary to provide sampling configuration."
            assert getattr(node, "spread",
                           False) == False or sampling_config.all_variations is None, "Cannot define `all_variations` for spread sampling nodes"
            spread = getattr(node, "spread", False)
            self.sampling_mode = "spread" if spread else "extend" if sampling_config.all_variations else "first"

        assert not self.greedy or self.data_store, (
            f"Node {str(self.node)} is greedy but does not provide a store to cache results!"
        )

    def is_sampling(self) -> bool:
        """
        Whether this node depends on sampling operations (i.e., its dependencies start with `sampled_`).

        Returns:
            True if node has at least one `sampled_` dependency.
        """
        return any(dep.startswith("sampled_") for dep in self.requires)

    @property
    def requires(self) -> List[str]:
        """
        List of dependency names required by this node.

        Returns:
            List of dependency identifiers.
        """
        return self.node.requires

    @property
    def description(self) -> Union[str, None]:
        """
        List of dependency names required by this node.

        Returns:
            List of dependency identifiers.
        """
        return getattr(self.node, "description", None)

    @property
    def provides(self) -> List[str]:
        """
        Names of the statistics generated by this node.

        Returns:
            List of stat identifiers.
        """
        return getattr(self.node, "provides", [])

    @property
    def id(self) -> str:
        """
        Identifier of the held node.

        Returns:
            Id of the node.
        """
        if self._id:
            return self._id
        if hasattr(self.node, "id"):
            return self.node.id
        return self.node.__class__.__name__

    def __str__(self) -> str:
        """
        String representation of the node configuration.

        Returns:
            String name or description of the node.
        """
        return str(self.node)
