try:
    from graphviz import Digraph
except ImportError as e:
    raise ImportError(
        "To use this functionality, you need to install the 'graphviz' module: `pip install graphviz`"
    ) from e

import logging

from ..acyclic_directed_graph import AcyclicDirectedGraph

log = logging.getLogger(__name__)


def split_after_words(text: str, limit: int = 30):
    text = text.strip()
    lines = []
    while text:
        if len(text) <= limit:
            lines.append(text)
            break
        idx = text.find(" ", limit)
        if idx == -1:  # no more spaces → take the rest
            lines.append(text)
            break
        lines.append(text[:idx].strip())
        text = text[idx + 1:].strip()
    return lines


def visualize_graph(acyclic_directed_graph: AcyclicDirectedGraph, to_console=True, to_pdf=False,
                    output_file="execution_graph",
                    show_descriptions=True, resolved_counts=None, include_removed=False):
    """
    Visualizes the graph using the Graphviz library and outputs it to console and/ or renders it to a file, depending on the parameters.
    """
    if not to_console and not to_pdf:
        log.warning("At least one output target (console, pdf) must be set to True")
        return
    if acyclic_directed_graph is None:
        log.warning("Cannot visualize empty graph: provided acyclic_directed_graph is None!")
        return

    dot = Digraph(comment="Execution Graph generated by async-graph-bench")
    dot.attr('node', shape='plaintext')  # Use HTML-like labels

    # Collect all nodes
    all_nodes = (
            {acyclic_directed_graph.data_source}
            | acyclic_directed_graph.optional_nodes_configs
            | acyclic_directed_graph.greedy_nodes_configs
    )

    if include_removed:
        all_nodes |= acyclic_directed_graph.unreachable_nodes | acyclic_directed_graph.pruned_nodes

    for node_config in all_nodes:
        deps = set(getattr(node_config, "dependencies", []))
        stats = getattr(node_config, "stats", [])
        # Also include sampling dependencies if present
        sampling_deps = acyclic_directed_graph.sampling.get(node_config, set())
        sampling_deps = {"sampled_" + dep for dep in sampling_deps}
        all_deps = deps | sampling_deps
        resolved = ""
        if resolved_counts and node_config.id in resolved_counts:
            resolved_counts_for_node = resolved_counts[node_config.id]
            resolved = f"{resolved_counts_for_node[0]}/{resolved_counts_for_node[1]}"
            resolved = f"<BR/><FONT POINT-SIZE=\"10\">{resolved}</FONT>"

        node_description = getattr(node_config, "description", None)
        if show_descriptions and node_description is not None:
            node_description = "<BR/>".join(split_after_words(node_description))
            node_description = f"<BR/><FONT POINT-SIZE=\"10\">{node_description}</FONT>" if node_description != "" else ""
        else:
            node_description = ""
        # Build HTML label
        id = node_config.id
        color = "#B0D0D0"
        if node_config in acyclic_directed_graph.unreachable_nodes:
            color = "#FFA593"
            id += " (unreachable)"
        if node_config in acyclic_directed_graph.pruned_nodes:
            color = "#FFA593"
            id += " (pruned)"

        label = f"""<
        <TABLE BORDER="1" CELLBORDER="1" CELLSPACING="0">
            <TR><TD>{", ".join(all_deps) if all_deps else "-"}</TD></TR>
            <TR><TD BGCOLOR="{color}" WIDTH="20"><B>{id}</B>{resolved}{node_description}</TD></TR>
            <TR><TD>{", ".join(stats) if stats else "-"}</TD></TR>
        </TABLE>
        >"""

        dot.node(node_config.id, label=label)

    # Add edges
    for producer, consumers in acyclic_directed_graph.edges.items():
        for consumer in consumers:
            dot.edge(producer.id, consumer.id)

    # Render the graph
    if to_console:
        print(dot.source)
    if to_pdf:
        dot.render(output_file, view=True)
