import logging

from ..acyclic_directed_graph import AcyclicDirectedGraph

log = logging.getLogger(__name__)


def split_after_words(text: str, limit: int = 30):
    text = text.strip()
    lines = []
    while text:
        if len(text) <= limit:
            lines.append(text)
            break
        idx = text.find(" ", limit)
        if idx == -1:  # no more spaces → take the rest
            lines.append(text)
            break
        lines.append(text[:idx].strip())
        text = text[idx + 1:].strip()
    return lines


def visualize_graph(
    acyclic_directed_graph: AcyclicDirectedGraph,
    format: str = "png",
    output_file_name: str = "execution_graph",
    show_descriptions: bool = True,
    resolved_counts: dict[str, tuple[int, int]] | None = None,
    include_removed: bool = False,
):
    """
    Visualizes an AcyclicDirectedGraph using the Graphviz library.

    The function generates a directed graph visualization of the provided
    `AcyclicDirectedGraph` instance. The output format determines whether
    the DOT source is printed to the console or rendered to a file.

    Each node is represented as a table containing its dependencies, ID,
    and provided outputs, with optional description and resolution statistics.
    Nodes marked as unreachable or pruned are visually distinguished by color.

    Args:
        acyclic_directed_graph (AcyclicDirectedGraph):
            The acyclic directed graph instance to visualize.

        format (str, default="png"):
            Output format for the visualization. Supported values:
              - `"console"`: print the Graphviz DOT source to stdout.
              - `"pdf"`: render to a PDF file.
              - `"png"`: render to a PNG image.
              - `"svg"`: render to an SVG image.

        output_file_name (str, default="execution_graph"):
            Base filename (without extension) for the rendered output.

        show_descriptions (bool, default=True):
            Whether to display node descriptions (if available) in the visualization.

        resolved_counts (dict[str, tuple[int, int]] | None, default=None):
            Optional mapping from node ID to a tuple `(resolved, total)` indicating
            resolution progress. Displays these counts in the node label.

        include_removed (bool, default=False):
            If True, includes nodes marked as unreachable or pruned in the visualization.

    Returns:
        None

    Warnings:
        Logs a warning and returns early if:
            - The provided `acyclic_directed_graph` is None.
            - The provided `format` is invalid.

    Notes:
        - Requires the `graphviz` Python package (`pip install graphviz`).
        - Each node is drawn as an HTML-like table with three rows:
            1. Required dependencies (or "-")
            2. Node ID (colored cell, with optional description and resolved count)
            3. Provided dependencies (or "-")
        - Unreachable and pruned nodes are highlighted in light orange (#FFA593).
    """
    try:
        from graphviz import Digraph
    except ImportError as e:
        raise ImportError(
            "To use this functionality, install the 'graphviz' module: `pip install graphviz`"
        ) from e

    valid_formats = {"console", "pdf", "png", "svg"}
    if format not in valid_formats:
        log.warning(f"Invalid format '{format}'. Must be one of {valid_formats}.")
        return

    if acyclic_directed_graph is None:
        log.warning("Cannot visualize empty graph: provided acyclic_directed_graph is None!")
        return

    dot = Digraph(comment="Execution Graph generated by async-graph-bench")
    dot.attr("node", shape="plaintext")  # Use HTML-like labels

    # Collect all nodes
    all_nodes = (
        {acyclic_directed_graph.data_source}
        | acyclic_directed_graph.optional_nodes_configs
        | acyclic_directed_graph.greedy_nodes_configs
    )

    if include_removed:
        all_nodes |= acyclic_directed_graph.unreachable_nodes | acyclic_directed_graph.pruned_nodes

    for node_config in all_nodes:
        required_deps = set(getattr(node_config, "requires", []))
        provided_deps = getattr(node_config, "provides", [])
        # Include sampling dependencies if present
        sampling_deps = acyclic_directed_graph.sampling.get(node_config, set())
        sampling_deps = {"sampled_" + dep for dep in sampling_deps}
        all_deps = required_deps | sampling_deps

        resolved = ""
        if resolved_counts and node_config.id in resolved_counts:
            res, total = resolved_counts[node_config.id]
            resolved = f"<BR/><FONT POINT-SIZE=\"10\">{res}/{total}</FONT>"

        node_description = getattr(node_config, "description", None)
        if show_descriptions and node_description:
            node_description = "<BR/>".join(split_after_words(node_description))
            node_description = f"<BR/><FONT POINT-SIZE=\"10\">{node_description}</FONT>"
        else:
            node_description = ""

        id = node_config.id
        color = "#B0D0D0"
        if node_config in acyclic_directed_graph.unreachable_nodes:
            color = "#FFA593"
            id += " (unreachable)"
        elif node_config in acyclic_directed_graph.pruned_nodes:
            color = "#FFA593"
            id += " (pruned)"

        label = f"""<
        <TABLE BORDER="1" CELLBORDER="1" CELLSPACING="0">
            <TR><TD>{", ".join(all_deps) if all_deps else "-"}</TD></TR>
            <TR><TD BGCOLOR="{color}" WIDTH="20"><B>{id}</B>{resolved}{node_description}</TD></TR>
            <TR><TD>{", ".join(provided_deps) if provided_deps else "-"}</TD></TR>
        </TABLE>
        >"""
        dot.node(node_config.id, label=label)

    # Add edges
    for producer, consumers in acyclic_directed_graph.edges.items():
        for consumer in consumers:
            dot.edge(producer.id, consumer.id)

    # Output
    if format == "console":
        print(dot.source)
    else:
        dot.render(output_file_name, view=False, format=format)

